# Workflow para construir un proyecto con Java y Angular sin ejecutar tests

name: Build Java and Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout del c칩digo
    - uses: actions/checkout@v4

    # Configuraci칩n de JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Compilar el backend con Maven sin ejecutar tests
    - name: Build API with Maven
      run: mvn -B package -DskipTests --file ./api/pom.xml

    # Configuraci칩n de Node.js para el frontend Angular
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Instalar dependencias de Angular
    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./frontend

    # Compilar el frontend de Angular
    - name: Build Angular frontend
      run: npm run build
      working-directory: ./frontend

    # Opcional: Subir el gr치fico de dependencias de Maven para Dependabot
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
